apiVersion: v1
kind: Service
metadata:
  name: python-service
spec:
  type: NodePort
  selector:
    app: python
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  # Optional: fixed port on the node

